package test.p59.test_rest.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2022-01-31T19:59:51.481-05:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "ServicesVehiculoService", 
                  wsdlLocation = "http://localhost:8080/Test-Rest/ServicesVehiculo?wsdl",
                  targetNamespace = "http://soap.Test_Rest.p59.test/") 
public class ServicesVehiculoService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soap.Test_Rest.p59.test/", "ServicesVehiculoService");
    public final static QName ServicesVehiculoPort = new QName("http://soap.Test_Rest.p59.test/", "ServicesVehiculoPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/Test-Rest/ServicesVehiculo?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServicesVehiculoService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/Test-Rest/ServicesVehiculo?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServicesVehiculoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServicesVehiculoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicesVehiculoService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServicesVehiculoService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServicesVehiculoService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ServicesVehiculoService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ServicesVehiculo
     */
    @WebEndpoint(name = "ServicesVehiculoPort")
    public ServicesVehiculo getServicesVehiculoPort() {
        return super.getPort(ServicesVehiculoPort, ServicesVehiculo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicesVehiculo
     */
    @WebEndpoint(name = "ServicesVehiculoPort")
    public ServicesVehiculo getServicesVehiculoPort(WebServiceFeature... features) {
        return super.getPort(ServicesVehiculoPort, ServicesVehiculo.class, features);
    }

}
