package test.p59.test_rest.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2022-01-31T19:59:51.468-05:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://soap.Test_Rest.p59.test/", name = "ServicesVehiculo")
@XmlSeeAlso({ObjectFactory.class})
public interface ServicesVehiculo {

    @WebMethod
    @RequestWrapper(localName = "getVehiculos", targetNamespace = "http://soap.Test_Rest.p59.test/", className = "test.p59.test_rest.soap.GetVehiculos")
    @ResponseWrapper(localName = "getVehiculosResponse", targetNamespace = "http://soap.Test_Rest.p59.test/", className = "test.p59.test_rest.soap.GetVehiculosResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<test.p59.test_rest.soap.Vehiculo> getVehiculos();

    @WebMethod
    @RequestWrapper(localName = "insertarVehiculo", targetNamespace = "http://soap.Test_Rest.p59.test/", className = "test.p59.test_rest.soap.InsertarVehiculo")
    @ResponseWrapper(localName = "insertarVehiculoResponse", targetNamespace = "http://soap.Test_Rest.p59.test/", className = "test.p59.test_rest.soap.InsertarVehiculoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String insertarVehiculo(
        @WebParam(name = "arg0", targetNamespace = "")
        test.p59.test_rest.soap.Vehiculo arg0
    );
}
