
package test.p59.test_rest.soap;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2022-01-31T19:59:51.314-05:00
 * Generated source version: 2.7.11
 * 
 */
public final class ServicesVehiculo_ServicesVehiculoPort_Client {

    private static final QName SERVICE_NAME = new QName("http://soap.Test_Rest.p59.test/", "ServicesVehiculoService");

    private ServicesVehiculo_ServicesVehiculoPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ServicesVehiculoService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ServicesVehiculoService ss = new ServicesVehiculoService(wsdlURL, SERVICE_NAME);
        ServicesVehiculo port = ss.getServicesVehiculoPort();  
        
        {
        System.out.println("Invoking getVehiculos...");
        java.util.List<test.p59.test_rest.soap.Vehiculo> vehiculos = port.getVehiculos();
        //System.out.println("getVehiculos.result=" + _getVehiculos__return);
        System.out.println("T: "+vehiculos.size());
        for(Vehiculo elemento: vehiculos) {
        	System.out.println("PLACA:"+elemento.getPlaca()+" MODELO: "+elemento.getModelo());
        }


        }
        
        {
        System.out.println("Invoking insertarVehiculo...");
        test.p59.test_rest.soap.Vehiculo vehiculo = new Vehiculo();
        Persona persona= new Persona();
        persona.setCodigo("01070");
        //persona.setApellido("Alvarez");
        //persona.setNombre("Juan");
        vehiculo.setPlaca("ABC4");
        vehiculo.setModelo("Raise2");
        vehiculo.setMarca("Mercedes");
        vehiculo.setPersona(persona);
        java.lang.String _insertarVehiculo__return = port.insertarVehiculo(vehiculo);
        System.out.println("Verificacion=" + _insertarVehiculo__return);

        }
        
        System.exit(0);
    }

}
